# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.12.8
    hooks:
      - id: sourcery
